# Generated by Django 5.2.17 on 2026-09-28 19:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x402f", "0011_delete_bazaar_catalog_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvarDelegationRegistration",
            fields=[
                ("intent_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("agent_id", models.UUIDField()),
                ("owner_account_id", models.CharField(max_length=64)),
                ("agent_version_id", models.UUIDField()),
                ("payee_revision", models.PositiveIntegerField()),
                ("recipient", models.CharField(max_length=42)),
                ("network", models.CharField(max_length=32)),
                ("asset", models.CharField(max_length=42)),
                ("amount_atomic", models.CharField(max_length=5)),
                ("terms_digest", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
