# Generated by Django 5.2.17 on 2026-09-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x402f", "0012_envardelegationregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvarDelegationAuthorization",
            fields=[
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="authorization_binding",
                        serialize=False,
                        to="x402f.envardelegationregistration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envar_delegation_binding",
                        to="x402f.x402authorization",
                    ),
                ),
            ],
        ),
    ]
